### ISSUE TITLE
GGA parsing is wrong

### ISSUE THREAD

**Issue by dvtomas** [ahmtcn123/Rust-NMEA#3]
The nice thing about this library is that it's small and no-deps. The bad thing is that GGA parsing is quite wrong.

Also, the errors are not useful, reporting "bad integer" and not telling which field failed to parse does not really help.

I refer to the format specified here: https://shadyelectronics.com/gps-nmea-sentence-structure/

So far I've found the following problems:

## 1. Incorrect longitude parsing

`$GPGGA,161009.00,1122.20418,N,02339.35234,E,1,08,1.09,11.5,M,11.3,M,,*62`
 
now parses as `lon: Cordinate { degree: 2, minute: 339.42234}`

but it should parse as `lon: Cordinate {degree: 23, minute: 39.42234}`

## 2. DGPSAge field should be a f32, not usize

It has a `x.x` format, so it will fail to parse as a usize.

## 3. Timestamp may occur that does NOT contain decimal separator and fractions

I've seen this, but the parser doesn't support that

**Comment by dvtomas** [comment]
Also, coordinates should be stored as f64, not f32, the precision of f32 is NOT enough for GPS data.

**Comment by dvtomas** [comment]
Also, there are three(!) `unwrap`()s in the `parse_line` fn, that is not safe.

**Comment by ahmetcanaksu** [comment]
Hello, thanks for such a good report. I will look into it.

**Comment by bill-callahan** [comment]
Hello,
I ran into issue with longitude coming back incorrect (ie.  lon.degree = 14, lon.minute = 504.xx)...it should come back with 145 degrees, 04 minutes....  I was using RMC strings, so i was able to fix with simple change on lines 85 & 86 of rmc.rs

let longitude_degree: usize = command[4][..3].parse()?;
        let longitude_minute: f32 = command[4][3..].parse()?;
        
original was [..2]....  changed to [..3].....  did cargo clean, cargo build, & cargo run... works as expected.

Not sure about the other issues people are having...Hope this helps.  BTW: i noticed the other commands (GGA & example) have a similar longitude parsing issue..

Bill

**Comment by ahmetcanaksu** [comment]
> Hello, I ran into issue with longitude coming back incorrect (ie. lon.degree = 14, lon.minute = 504.xx)...it should come back with 145 degrees, 04 minutes.... I was using RMC strings, so i was able to fix with simple change on lines 85 & 86 of rmc.rs
> 
> let longitude_degree: usize = command[4][..3].parse()?; let longitude_minute: f32 = command[4][3..].parse()?;
> 
> original was [..2].... changed to [..3]..... did cargo clean, cargo build, & cargo run... works as expected.
> 
> Not sure about the other issues people are having...Hope this helps. BTW: i noticed the other commands (GGA & example) have a similar longitude parsing issue..
> 
> Bill

Hello Bill,

Thanks for reporting the issue I'll fix it along with my non-rusty code patterns.

**Comment by ahmetcanaksu** [comment]
Hello again! I fixed the issues it took some time since I am working at fulltime job, thanks for feedback
